import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

FIELDS = {
	"Delivery Note": [
		{
			"fieldname": "astrasun_loading_section",
			"label": "Mill loading",
			"fieldtype": "Section Break",
			"insert_after": "scan_barcode",
			"collapsible": 1,
		},
		{
			"fieldname": "astrasun_loading_status",
			"label": "Loading Status",
			"fieldtype": "Select",
			"options": "Loading\nLoaded\nDispatched\nDelivered",
			"default": "Loading",
			"in_list_view": 1,
			"in_standard_filter": 1,
			"no_copy": 1,
			"read_only": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_loading_section",
		},
		{
			"fieldname": "astrasun_vehicle_no",
			"label": "Vehicle Number",
			"fieldtype": "Data",
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_loading_status",
		},
		{
			"fieldname": "astrasun_driver_name",
			"label": "Driver",
			"fieldtype": "Data",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_vehicle_no",
		},
		{
			"fieldname": "astrasun_driver_phone",
			"label": "Driver Phone",
			"fieldtype": "Data",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_driver_name",
		},
		{
			"fieldname": "astrasun_driver_user",
			"label": "Driver's App Login",
			"fieldtype": "Link",
			"options": "User",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_driver_phone",
		},
		{
			"fieldname": "astrasun_invoice",
			"label": "Invoice",
			"fieldtype": "Link",
			"options": "Sales Invoice",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_driver_user",
		},
		{
			"fieldname": "astrasun_eway_bill_no",
			"label": "E-way Bill Number",
			"fieldtype": "Data",
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_invoice",
		},
		{
			"fieldname": "astrasun_received_by",
			"label": "Received By",
			"fieldtype": "Data",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_eway_bill_no",
		},
		{
			"fieldname": "astrasun_delivered_at",
			"label": "Delivered At",
			"fieldtype": "Datetime",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_received_by",
		},
		{
			"fieldname": "astrasun_delivery_remarks",
			"label": "Delivery Remarks",
			"fieldtype": "Small Text",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_delivered_at",
		},
		{
			"fieldname": "astrasun_loaded_by",
			"label": "Loaded By",
			"fieldtype": "Link",
			"options": "User",
			"read_only": 1,
			"no_copy": 1,
			"allow_on_submit": 1,
			"insert_after": "astrasun_delivery_remarks",
		},
	]
}


def setup_loading_fields():
	create_custom_fields(FIELDS, update=True)
