import 'package:flutter/widgets.dart';

/// All app text in English and Hindi. Keys are English so a missing Hindi
/// string still shows something readable.
const Map<String, Map<String, String>> _strings = {
  'hi': {
    'Atulyaa Mill': 'अतुल्य मिल',
    'Server address': 'सर्वर पता',
    'User ID': 'यूज़र आईडी',
    'Password': 'पासवर्ड',
    'Log in': 'लॉग इन करें',
    'Log out': 'लॉग आउट',
    'Wrong user ID or password': 'यूज़र आईडी या पासवर्ड गलत है',
    'Cannot reach the server. Check the internet.':
        'सर्वर से संपर्क नहीं हो पा रहा। इंटरनेट देखें।',
    'Namaste, {0}': 'नमस्ते, {0}',
    'What to do now': 'अभी क्या करना है',
    'No work assigned to your role yet. Ask the manager.':
        'आपके काम के लिए अभी कुछ तय नहीं है। मैनेजर से पूछें।',
    'Coming soon': 'जल्द आ रहा है',
    'This screen is being built.': 'यह स्क्रीन बन रही है।',
    'Back': 'वापस',
    'Speak': 'बोलें',
    'Listening...': 'सुन रहे हैं...',
    'Voice input is not available on this phone':
        'इस फ़ोन पर बोलकर लिखना उपलब्ध नहीं है',
    'Try voice input': 'बोलकर लिखें',
    'Remarks': 'टिप्पणी',
    'Try demo': 'डेमो देखें',
    'The mill server is not set up yet. Try the demo.':
        'मिल का सर्वर अभी तैयार नहीं है। डेमो देखें।',
    'Who are you?': 'आप कौन हैं?',
    'Demo: sample data, nothing is saved':
        'डेमो: नमूना डेटा, कुछ भी सेव नहीं होता',
    'Owner': 'मालिक',
    'Manager': 'मैनेजर',
    'Sales': 'सेल्स',
    'Purchase': 'खरीद',
    'Gate / weighbridge': 'गेट / कांटा',
    'Lab': 'लैब',
    'Mill operator': 'मिल ऑपरेटर',
    'Packing': 'पैकिंग',
    'Loading': 'लोडिंग',
    'Dispatch': 'डिस्पैच',
    'Driver': 'ड्राइवर',
    'Accounts': 'अकाउंट्स',
    'Auditor': 'ऑडिटर',
    'Choose customer': 'ग्राहक चुनें',
    'Add bags': 'बोरी जोड़ें',
    'Total': 'कुल',
    'Send for approval': 'मंज़ूरी के लिए भेजें',
    'Sent for approval': 'मंज़ूरी के लिए भेज दिया',
    'Could not save. Try again.': 'सेव नहीं हुआ। दोबारा कोशिश करें।',
    'Approve': 'मंज़ूर करें',
    'Reject': 'मना करें',
    'Send back': 'वापस भेजें',
    'Reason': 'कारण',
    'Done': 'ठीक है',
    'No orders waiting for you': 'आपके लिए कोई ऑर्डर बाकी नहीं',
    'No orders yet': 'अभी कोई ऑर्डर नहीं',
    'Over credit limit': 'उधार सीमा से ऊपर',
    'Stock is short': 'स्टॉक कम है',
    'Dues {0} + this order = {1} of limit {2}':
        'बकाया {0} + यह ऑर्डर = {1}, सीमा {2}',
    'Draft': 'ड्राफ्ट',
    'Pending Approval': 'मंज़ूरी बाकी',
    'Approved': 'मंज़ूर',
    'Rejected': 'मना किया',
    'Sent Back': 'वापस भेजा',
    // Loading
    'bags': 'बोरी',
    'Waiting': 'इंतज़ार में',
    'Loaded': 'लोड हो गया',
    'Start loading': 'लोडिंग शुरू करें',
    'Mark loaded': 'लोड पूरा',
    'Vehicle number': 'गाड़ी नंबर',
    'Enter the vehicle number': 'गाड़ी नंबर लिखें',
    'Nothing to load': 'लोड करने को कुछ नहीं',
    'Bags loaded': 'लोड की गई बोरी',
    'Vehicle {0}': 'गाड़ी {0}',
    'No trucks waiting': 'कोई ट्रक इंतज़ार में नहीं',
    'E-way bill number': 'ई-वे बिल नंबर',
    'Needed when goods are over ₹50,000': '₹50,000 से ज़्यादा माल पर ज़रूरी',
    'Make invoice': 'बिल बनाएं',
    'Invoice': 'बिल',
    'Invoice made': 'बिल बन गया',
    'Let truck leave': 'ट्रक रवाना करें',
    'Truck left': 'ट्रक रवाना हुआ',
    'Received by': 'माल लेने वाले का नाम',
    'Confirm delivery': 'डिलीवरी पक्की करें',
    'Delivered': 'पहुंच गया',
    'Delivered to {0}': '{0} को दिया',
    'No deliveries waiting': 'कोई डिलीवरी बाकी नहीं',
    'Dues': 'बकाया',
    'Receive payment': 'भुगतान लें',
    'Amount received': 'मिली रकम',
    'Cash': 'नकद',
    'Bank': 'बैंक',
    'UTR or cheque number': 'UTR या चेक नंबर',
    'Nobody owes money': 'किसी का बकाया नहीं',
    'Received {0}, still due {1}': '{0} मिले, बाकी {1}',
    '{0} bills, oldest {1}': '{0} बिल, सबसे पुराना {1}',
    'Money goes to the oldest bill first':
        'पैसा सबसे पुराने बिल में पहले जाता है',
    'Supplier': 'सप्लायर',
    'Truck entered': 'ट्रक की एंट्री हो गई',
    'Weight on supplier slip (kg)': 'सप्लायर की पर्ची का वज़न (किलो)',
    'Rate per quintal': 'भाव प्रति क्विंटल',
    'Enter truck': 'ट्रक की एंट्री करें',
    'Supplier slip': 'सप्लायर पर्ची',
    'Loaded weight': 'भरे ट्रक का वज़न',
    'Loaded truck weight (kg)': 'भरे ट्रक का वज़न (किलो)',
    'Empty truck weight (kg)': 'खाली ट्रक का वज़न (किलो)',
    'Save loaded weight': 'भरा वज़न सेव करें',
    'Unloaded, save': 'खाली हुआ, सेव करें',
    'Weight is different from the slip: {0}': 'वज़न पर्ची से अलग है: {0}',
    'Wheat received: {0}': 'गेहूं मिला: {0}',
    'At Gate': 'गेट पर',
    'Weighed In': 'वज़न हुआ',
    'On Hold': 'रोका गया',
    'Released': 'पास',
    'Received': 'जमा हुआ',
    'Moisture': 'नमी',
    'Foreign matter': 'कचरा / मिलावट',
    'Broken grain': 'टूटा दाना',
    'Release': 'पास करें',
    'Hold': 'रोकें',
    'Wheat in stock': 'गोदाम में गेहूं',
    'Morning': 'सुबह',
    'Afternoon': 'दोपहर',
    'Night': 'रात',
    'Wheat ground': 'पिसा हुआ गेहूं',
    'Tempering water': 'तड़का पानी',
    'Atta': 'आटा',
    'Maida': 'मैदा',
    'Sooji': 'सूजी',
    'Chokar': 'चोकर',
    'Extraction': 'एक्सट्रैक्शन',
    'Total output': 'कुल उत्पादन',
    'Save batch': 'बैच सेव करें',
    'Low yield: {0}% extraction, loss {1} kg':
        'कम उपज: {0}% एक्सट्रैक्शन, नुकसान {1} किलो',
    'Batch saved: {0}% extraction': 'बैच सेव हुआ: {0}% एक्सट्रैक्शन',
    'Machine': 'मशीन',
    'Minutes stopped': 'कितने मिनट बंद',
    'Downtime saved': 'मशीन बंद दर्ज हुआ',
    'Save': 'सेव करें',
    'Packed bags': 'पैक बोरी',
    'Empty bags': 'खाली बोरी',
    'Bulk flour': 'खुला आटा',
    'Can pack up to {0} bags': 'अधिकतम {0} बोरी पैक हो सकती हैं',
    'Bags to pack': 'पैक करने की बोरी',
    'Pack': 'पैक करें',
    'Packed: {0} bags': 'पैक हुईं: {0} बोरी',
    'Raw': 'कच्चा माल',
    'Bulk': 'खुला माल',
    'Packed': 'पैक माल',
    'kg': 'किलो',
    'Sales booked': 'आज की बिक्री',
    'Invoiced': 'बिल बने',
    'Collected': 'वसूली',
    'Orders to approve': 'मंज़ूरी बाकी ऑर्डर',
    'Wheat trucks in yard': 'यार्ड में गेहूं ट्रक',
    'Dues by age': 'बकाया, पुराना कितना',
    'days': 'दिन',
    'Nothing needs a look': 'कुछ भी देखने लायक नहीं',
    // Tasks
    'Approve orders': 'ऑर्डर मंज़ूर करें',
    'Today at the mill': 'आज मिल में',
    'Alerts': 'अलर्ट',
    'Plan production': 'उत्पादन योजना',
    'Trucks at the mill': 'मिल में ट्रक',
    'Stock': 'स्टॉक',
    'New order': 'नया ऑर्डर',
    'My orders': 'मेरे ऑर्डर',
    'Customer dues': 'ग्राहक बकाया',
    'Wheat purchase': 'गेहूं खरीद',
    'Supplier rates': 'सप्लायर रेट',
    'Truck entry': 'ट्रक एंट्री',
    'Weighbridge': 'कांटा',
    'Check wheat lot': 'गेहूं लॉट जांच',
    'Check flour': 'आटा जांच',
    'Start milling batch': 'पिसाई शुरू करें',
    'Report downtime': 'मशीन बंद दर्ज करें',
    'Pack bags': 'बोरी पैक करें',
    'Loading queue': 'लोडिंग सूची',
    'Send trucks': 'ट्रक रवाना करें',
    'My deliveries': 'मेरी डिलीवरी',
    'Collect payment': 'भुगतान लें',
    'Bills and payments': 'बिल और भुगतान',
    'Change log': 'बदलाव लॉग',
  },
};

class S {
  S(this.languageCode);
  final String languageCode;

  static S of(BuildContext context) =>
      S(Localizations.localeOf(context).languageCode);

  String t(String key, [List<Object> args = const []]) {
    var text = _strings[languageCode]?[key] ?? key;
    for (var i = 0; i < args.length; i++) {
      text = text.replaceAll('{$i}', '${args[i]}');
    }
    return text;
  }
}
